meta_product_name: "FolioChat"
meta_title: "FolioChat - Smart Portfolio with Integrated Chatbot"
meta_description: "Discover FolioChat, an innovative portfolio integrated with a smart chatbot. Explore my projects and interact with Folio for a unique and personalized experience."
meta_image: "foliochatbanner.jpg"
